// Sample Data for JAY Real Estate
// Based on fam Properties structure and real Dubai market data

// Sample Properties Data
const sampleProperties = [
  {
    id: 1,
    title: "Luxury Downtown Apartment",
    price: 2500000,
    currency: "AED",
    pricePerSqft: 2083,
    type: "apartment",
    transactionType: "buy",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    areaUnit: "sqft",
    location: "Downtown Dubai",
    community: "Downtown Dubai",
    building: "Burj Vista",
    developer: "Emaar Properties",
    projectName: "Downtown Views",
    features: ["Balcony", "City View", "Parking", "Built-in Wardrobes"],
    description: "Stunning 2-bedroom apartment in the heart of Downtown Dubai with breathtaking city views",
    amenities: ["Swimming Pool", "Gym", "Concierge", "Security", "Valet Parking"],
    paymentPlan: "70/30 Payment Plan",
    completionDate: "2024-12-31",
    serviceCharge: 12,
    furnished: true,
    luxury: true,
    status: "ready",
    parking: 1,
    balcony: true,
    roi: 7.5,
    rentalYield: 6.2,
    dldNumber: "DLD-001-2024",
    reraNumber: "RERA-001-2024",
    listedDate: "2024-01-15",
    views: 245,
    inquiries: 18
  },
  {
    id: 2,
    title: "Modern Business Bay Villa",
    price: 4500000,
    currency: "AED",
    pricePerSqft: 1286,
    type: "villa",
    transactionType: "buy",
    bedrooms: 4,
    bathrooms: 5,
    area: 3500,
    areaUnit: "sqft",
    location: "Business Bay",
    community: "Business Bay",
    building: "Bay Villas",
    developer: "DAMAC Properties",
    projectName: "Bay Residences",
    features: ["Private Garden", "Maid's Room", "Study Room", "Laundry Room"],
    description: "Spacious 4-bedroom villa with modern amenities and private garden",
    amenities: ["Private Pool", "Garden", "Garage", "Security", "Playground"],
    paymentPlan: "60/40 Payment Plan",
    completionDate: "2025-06-30",
    serviceCharge: 8,
    luxury: true,
    status: "under-construction",
    parking: 2,
    maidRoom: true,
    studyRoom: true,
    laundryRoom: true,
    roi: 8.2,
    rentalYield: 7.1,
    dldNumber: "DLD-002-2024",
    reraNumber: "RERA-002-2024",
    listedDate: "2024-02-01",
    views: 189,
    inquiries: 23
  },
  {
    id: 3,
    title: "Palm Jumeirah Beachfront Penthouse",
    price: 8500000,
    currency: "AED",
    pricePerSqft: 3036,
    type: "penthouse",
    transactionType: "buy",
    bedrooms: 3,
    bathrooms: 4,
    area: 2800,
    areaUnit: "sqft",
    location: "Palm Jumeirah",
    community: "Palm Jumeirah",
    building: "Azure Residences",
    developer: "Nakheel",
    projectName: "Palm Azure",
    features: ["Beach Access", "Private Terrace", "Sea View", "Jacuzzi"],
    description: "Exclusive beachfront penthouse with panoramic sea views and private beach access",
    amenities: ["Beach Access", "Spa", "Marina", "Restaurants", "Concierge"],
    paymentPlan: "50/50 Payment Plan",
    completionDate: "2024-03-31",
    serviceCharge: 15,
    furnished: true,
    luxury: true,
    beachfront: true,
    status: "ready",
    parking: 2,
    balcony: true,
    roi: 6.8,
    rentalYield: 5.5,
    dldNumber: "DLD-003-2024",
    reraNumber: "RERA-003-2024",
    listedDate: "2024-01-20",
    views: 412,
    inquiries: 35
  },
  {
    id: 4,
    title: "Dubai Marina Waterfront Apartment",
    price: 1800000,
    currency: "AED",
    pricePerSqft: 1800,
    type: "apartment",
    transactionType: "buy",
    bedrooms: 1,
    bathrooms: 2,
    area: 1000,
    areaUnit: "sqft",
    location: "Dubai Marina",
    community: "Dubai Marina",
    building: "Marina Heights",
    developer: "Select Group",
    projectName: "Marina Living",
    features: ["Marina View", "Balcony", "Parking", "Storage"],
    description: "Modern 1-bedroom apartment with stunning marina views",
    amenities: ["Swimming Pool", "Gym", "Marina Walk", "Restaurants"],
    paymentPlan: "80/20 Payment Plan",
    completionDate: "2024-08-31",
    serviceCharge: 10,
    waterfront: true,
    status: "ready",
    parking: 1,
    balcony: true,
    roi: 8.5,
    rentalYield: 7.8,
    dldNumber: "DLD-004-2024",
    reraNumber: "RERA-004-2024",
    listedDate: "2024-02-10",
    views: 156,
    inquiries: 12
  },
  {
    id: 5,
    title: "Jumeirah Golf Estates Villa",
    price: 6200000,
    currency: "AED",
    pricePerSqft: 1240,
    type: "villa",
    transactionType: "buy",
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    areaUnit: "sqft",
    location: "Jumeirah Golf Estates",
    community: "Jumeirah Golf Estates",
    building: "Golf Villas",
    developer: "Dubai Properties",
    projectName: "Golf Estate Homes",
    features: ["Golf Course View", "Private Pool", "Garden", "Garage"],
    description: "Luxurious 5-bedroom villa overlooking the championship golf course",
    amenities: ["Golf Course", "Club House", "Swimming Pool", "Tennis Court"],
    paymentPlan: "70/30 Payment Plan",
    completionDate: "2024-11-30",
    serviceCharge: 6,
    luxury: true,
    golfCourse: true,
    status: "ready",
    parking: 3,
    maidRoom: true,
    studyRoom: true,
    laundryRoom: true,
    roi: 7.8,
    rentalYield: 6.5,
    dldNumber: "DLD-005-2024",
    reraNumber: "RERA-005-2024",
    listedDate: "2024-01-25",
    views: 298,
    inquiries: 28
  }
];

// Sample Locations Data
const sampleLocations = [
  {
    id: 1,
    name: "Downtown Dubai",
    type: "district",
    description: "The heart of modern Dubai with iconic landmarks and world-class amenities",
    zone: 1,
    averagePrice: 1800,
    priceRange: { min: 800000, max: 15000000 },
    popularPropertyTypes: ["apartment", "penthouse"],
    amenities: ["Dubai Mall", "Burj Khalifa", "Dubai Fountain", "Metro Station"],
    nearbyLandmarks: ["Burj Khalifa", "Dubai Mall", "Opera District"],
    transportation: ["Dubai Metro", "Bus Routes", "Taxi Services"],
    schools: ["GEMS Wellington", "Dubai International Academy"],
    hospitals: ["Dubai Hospital", "Mediclinic City Hospital"],
    shoppingCenters: ["Dubai Mall", "Souk Al Bahar"],
    coordinates: { lat: 25.1972, lng: 55.2744 },
    distanceToAirport: 15,
    distanceToDowntown: 0,
    distanceToBeach: 12,
    investmentRating: 9,
    rentalDemand: "High"
  },
  {
    id: 2,
    name: "Business Bay",
    type: "district",
    description: "Dubai's business and financial district with modern skyscrapers",
    zone: 1,
    averagePrice: 1500,
    priceRange: { min: 600000, max: 8000000 },
    popularPropertyTypes: ["apartment", "office", "villa"],
    amenities: ["Canal Views", "Business Centers", "Restaurants", "Metro"],
    nearbyLandmarks: ["Dubai Canal", "Burj Khalifa", "DIFC"],
    transportation: ["Dubai Metro", "Water Taxi", "Bus Routes"],
    schools: ["Repton School", "JSS International"],
    hospitals: ["Mediclinic Parkview", "Canadian Medical Centre"],
    shoppingCenters: ["Bay Avenue", "Dubai Mall"],
    coordinates: { lat: 25.1877, lng: 55.2632 },
    distanceToAirport: 18,
    distanceToDowntown: 5,
    distanceToBeach: 15,
    investmentRating: 8,
    rentalDemand: "High"
  },
  {
    id: 3,
    name: "Palm Jumeirah",
    type: "island",
    description: "Iconic man-made island offering luxury beachfront living",
    zone: 2,
    averagePrice: 2500,
    priceRange: { min: 1500000, max: 50000000 },
    popularPropertyTypes: ["villa", "apartment", "penthouse"],
    amenities: ["Private Beaches", "Luxury Hotels", "Fine Dining", "Spa"],
    nearbyLandmarks: ["Atlantis Hotel", "Burj Al Arab", "Dubai Marina"],
    transportation: ["Palm Monorail", "Taxi Services", "Water Taxi"],
    schools: ["Regent International School", "GEMS Wellington"],
    hospitals: ["American Hospital", "Mediclinic Parkview"],
    shoppingCenters: ["Nakheel Mall", "Golden Mile Galleria"],
    coordinates: { lat: 25.1124, lng: 55.1390 },
    distanceToAirport: 35,
    distanceToDowntown: 25,
    distanceToBeach: 0,
    investmentRating: 9,
    rentalDemand: "Very High"
  }
];

// Sample Developers Data
const sampleDevelopers = [
  {
    id: 1,
    name: "Emaar Properties",
    logo: "/images/developers/emaar-logo.png",
    description: "Leading real estate developer in Dubai, creator of iconic landmarks",
    established: 1997,
    website: "https://www.emaar.com",
    projects: ["Downtown Dubai", "Dubai Marina", "Emirates Hills"],
    completedProjects: ["Burj Khalifa", "Dubai Mall", "Address Hotels"],
    upcomingProjects: ["Dubai Creek Harbour", "Emaar South"],
    totalUnits: 50000,
    rating: 4.8,
    specializations: ["luxury", "mixed-use", "hospitality"],
    popularLocations: ["Downtown Dubai", "Dubai Marina", "Arabian Ranches"],
    headquarters: "Dubai, UAE"
  },
  {
    id: 2,
    name: "DAMAC Properties",
    logo: "/images/developers/damac-logo.png",
    description: "Luxury real estate developer known for premium residential projects",
    established: 2002,
    website: "https://www.damacproperties.com",
    projects: ["DAMAC Hills", "Business Bay", "Dubai Marina"],
    completedProjects: ["DAMAC Towers", "Ocean Heights", "Park Towers"],
    upcomingProjects: ["DAMAC Lagoons", "DAMAC Islands"],
    totalUnits: 35000,
    rating: 4.6,
    specializations: ["luxury", "golf-course", "branded"],
    popularLocations: ["Business Bay", "DAMAC Hills", "Dubai Marina"],
    headquarters: "Dubai, UAE"
  },
  {
    id: 3,
    name: "Nakheel",
    logo: "/images/developers/nakheel-logo.png",
    description: "Master developer of iconic projects including Palm Jumeirah",
    established: 2000,
    website: "https://www.nakheel.com",
    projects: ["Palm Jumeirah", "The World Islands", "Dragon City"],
    completedProjects: ["Palm Jumeirah", "Ibn Battuta Mall", "Dragon City"],
    upcomingProjects: ["Palm Jebel Ali", "Deira Islands"],
    totalUnits: 40000,
    rating: 4.7,
    specializations: ["master-development", "islands", "retail"],
    popularLocations: ["Palm Jumeirah", "Deira", "International City"],
    headquarters: "Dubai, UAE"
  }
];

// Sample Agents Data
const sampleAgents = [
  {
    id: 1,
    name: "Ahmed Al Mansouri",
    photo: "/images/agents/ahmed.jpg",
    title: "Senior Property Consultant",
    experience: 8,
    languages: ["English", "Arabic", "Hindi"],
    specializations: ["Luxury Properties", "Downtown Dubai", "Investment"],
    locations: ["Downtown Dubai", "Business Bay", "DIFC"],
    phone: "+971 50 123 4567",
    email: "ahmed@jayrealestate.com",
    whatsapp: "+971 50 123 4567",
    rating: 4.9,
    propertiesSold: 156,
    propertiesRented: 89,
    clientSatisfaction: 98,
    reraLicense: "RERA-12345",
    certifications: ["RERA Certified", "Real Estate Investment Specialist"]
  },
  {
    id: 2,
    name: "Sarah Johnson",
    photo: "/images/agents/sarah.jpg",
    title: "Luxury Property Specialist",
    experience: 6,
    languages: ["English", "French", "Russian"],
    specializations: ["Beachfront Properties", "Palm Jumeirah", "Villas"],
    locations: ["Palm Jumeirah", "Dubai Marina", "Jumeirah"],
    phone: "+971 55 987 6543",
    email: "sarah@jayrealestate.com",
    whatsapp: "+971 55 987 6543",
    rating: 4.8,
    propertiesSold: 98,
    propertiesRented: 67,
    clientSatisfaction: 96,
    reraLicense: "RERA-67890",
    certifications: ["RERA Certified", "Luxury Property Specialist"]
  }
];

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    sampleProperties,
    sampleLocations,
    sampleDevelopers,
    sampleAgents
  };
}
